/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.videoCanvas[_ngcontent-%COMP%] {\r\n  position: absolute;\r\n  z-index: 10;\r\n}'];